//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMSSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string houseNum { get; set; }
        public string road { get; set; }
        public string subdistrictID { get; set; }
        public string homePhone { get; set; }
        public string mobilePhone { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<byte> isActive { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<byte> departmentID { get; set; }
        public string zipcode { get; set; }
        public string imageFileName { get; set; }
        public Nullable<byte> empType { get; set; }
        public string email { get; set; }
    }
}
